releases:
  - name: ingress-nginx
    namespace: ingress-nginx
    chart: ingress-nginx/ingress-nginx
    version: 4.10.1
    values:
      - controller:
          service:
            type: NodePort
            nodePorts:
              http: 32080
              https: 32443

  - name: nims-tofu-cloud
    namespace: default
    chart: ./nims-tofu-cloud
    values:
      - ./nims-tofu-cloud/values.yaml
